### ISSUE TITLE
opening multiple  visual studio instances (with different solutions) causes failures in WTS

### ISSUE THREAD

**Issue by amoldeshpande** [Microsoft/WindowsTemplateStudio#1004]
Windows Template Studio 2017-08-24 11:14:34.174
Version: 1.2.17198.1
>
========== Exception Tracked [20170824 11:14:32.140] ==========
[11:14:32.592 - Information]::Configuration file loaded: F:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\uguvjkvi.scm\WindowsTemplateStudio.config.json
Additional Message: The templates can't be extracted.
System.IO.IOException: The process cannot access the file 'F:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\uguvjkvi.scm\InstalledTemplates\Templates.mstx' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

**Comment by crutkas** [comment]
@amoldeshpande  Great catch!

@ralarcon I'm assuming we do readwrite opening here, any reason why versus just a read?  I would imagine a read would not be a blocking for multiple reads

**Comment by amoldeshpande** [comment]
Full stack may  help
```
System.IO.IOException: The process cannot access the file 'F:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\uguvjkvi.scm\InstalledTemplates\Templates.mstx' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnFile(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess)
   at Microsoft.Templates.Core.Locations.Templatex.Extract(String signedFilePack, String targetDirectory, Boolean verifySignatures)
   at Microsoft.Templates.Core.Locations.TemplatesSource.ExtractContent(String file, String tempFolder)
   at Microsoft.Templates.Core.Locations.TemplatesSource.ExtractMstx(String mstxFilePath)
   at Microsoft.Templates.Core.Locations.TemplatesSource.Extract(String mstxFilePath, String targetFolder)
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.ExtractInstalledContent()
```

**Comment by mrlacey** [comment]
Suspect this is partly linked to the issue identified in #919 where it's being overly aggressive in checking for (and downloading) template "updates".
My initial reaction is just that we can ignore this error as it's 2 separate processes copying from separate temp folders into a single folder. Probably be worth being a bit more thorough than just ignoring/suppressing the error though. 😉

**Comment by mrlacey** [comment]
X-Ref #928

**Comment by dgomezc** [comment]
Verified in dev-nightly
Wizard: 0.14.17250.65003
Templates: 0.14.17250.2
