### ISSUE TITLE
Warning on first template synchronization on dev-nightly

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1249]
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\WindowsTemplateStudio\Templates\Dev\.lock'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.SetInstanceSyncLock()

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.1
