### ISSUE TITLE
Error to add page from right click after select image gallery page

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1411]
### Repro steps:

1. Create new empty project.
2. From right click, Add new page, select ImageGallery and click to next button.
3. In change summary window click to back button.
4. Select blank page and add to project.

### Expected Behavior

New blank page added to project.

### Actual Behavior

COM Exception

Stack trace:
System.Runtime.InteropServices.COMException (0x80004005): Cannot find file "C:\Users\david\OneDrive\Documentos\Visual Studio 2017\Projects\App8\App8\Styles\Image.xaml".
   at EnvDTE.ProjectItems.AddFromFile(String FileName)
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.AddItems(String[] itemsFullPath)
   at Microsoft.Templates.Core.PostActions.Catalog.AddContextItemsToProjectPostAction.Execute()
   at Microsoft.Templates.UI.NewItemGenController.ExecuteSyncGenerationPostActions(TempGenerationResult result)
   at Microsoft.Templates.UI.NewItemGenController.UnsafeFinishGeneration(UserSelection userSelection)
   at Microsoft.Templates.UI.NewItemGenController.FinishGeneration(UserSelection userSelection)

![image](https://user-images.githubusercontent.com/12777039/32489922-bbea1072-c3b1-11e7-8e74-c81211970e38.png)

**Comment by mvegaca** [comment]
Checked on **Dev Nightly**
Wizard: 0.14.17314.65001
Templates: 0.14.17314.1
