### ISSUE TITLE
First time run in VS emulator, System.IO.IOException is thrown

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1464]
This has happened a few times on first time load from F5'ing inside the VS Emulator

Exception thrown: 'System.IO.IOException' in mscorlib.dll
[2017-11-21 14:43:14.196]	crutkas	23140(7)		Warning	The folder C:\ProgramData\WindowsTemplateStudio\Templates\Local\0.0.0.0 can't be delete. Error: The directory is not empty.
	Exception:

System.IO.IOException: The directory is not empty.

   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Microsoft.Templates.Core.Fs.SafeDeleteDirectory(String dir, Boolean warnOnFailure) in C:\Users\crutkas\Source\Repos\WTS\code\src\Core\Fs.cs:line 116
'VsEmulator.exe' (CLR v4.0.30319: VsEmulator.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'VsEmulator.exe' (CLR v4.0.30319: VsEmulator.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0xbd9c has exited with code 0 (0x0).

**Comment by crutkas** [comment]
@ralarcon has anyone looked at this?

**Comment by ralarcon** [comment]
@crutkas Yes, I forgot to track it. It should not happen with the new approach for local templates load for the emulator (included in the optimizations). Assigning it to me to double check and close.

**Comment by ralarcon** [comment]
Verified in 
Wizard: 0.16.18015.65002
Templates: 0.16.18015.3
