### ISSUE TITLE
WTS Update failed to install.

### ISSUE THREAD

**Issue by LanceMcCarthy** [Microsoft/WindowsTemplateStudio#1621]
### Installation Bug Report
Attempted to update WTS using Visual Studio 2017's built-in VSIX downloader/updater in the **Extensions and Updates** dialog.

After VS2017 shut down, I was prompted to complete the installation. I clicked okay, and the installation failed, 

Specific Error Message: `Install Error : System.InvalidOperationException: A value for 'Component' needs to be specified in the catalog.`

Here is the text from the relevant part of the install log:

```
12/27/2017 12:13:10 PM - Beginning to install extension to Microsoft Visual Studio Enterprise 2017...
12/27/2017 12:13:10 PM - Upgrading 'Windows Template Studio', version 1.5.17334.7 to version 1.6.17355.2.
12/27/2017 12:13:10 PM - VSIX TaskScheduler: VSIX Auto Updatetask does not exist.
12/27/2017 12:13:10 PM - VSIX TaskScheduler: VSIX Auto Updatetask has been successfully created.
12/27/2017 12:13:15 PM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.8: The current OS Version '10.0.16299.0' is not in the supported version range '[6.2,6.3)'.
12/27/2017 12:13:15 PM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.81: The current OS Version '10.0.16299.0' is not in the supported version range '[6.3,6.4)'.
12/27/2017 12:13:15 PM - Skipping non-applicable package Microsoft.Windows.D3DCompiler.Msu.Win7: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1,6.2)'.
12/27/2017 12:13:15 PM - Skipping non-applicable package Microsoft.Net.4.6.FullRedist.NonThreshold: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1.1,6.4)'.
12/27/2017 12:13:15 PM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.7: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1,6.2)'.
12/27/2017 12:13:15 PM - Skipping non-applicable package Microsoft.DiagnosticsHub.KB2882822.Win7: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1,6.2)'.
12/27/2017 12:13:15 PM - Skipping non-applicable package WebSocket4NetV2: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1,6.2)'.
12/27/2017 12:13:15 PM - Skipping non-applicable package Microsoft.Net.4.6.1.FullRedist.Threshold: The current OS Version '10.0.16299.0' is not in the supported version range '[10.0.10240]'.
12/27/2017 12:13:15 PM - Skipping non-applicable package Microsoft.Net.4.6.1.FullRedist.NonThreshold: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1.1,6.4)'.
12/27/2017 12:13:16 PM - Skipping non-applicable package Microsoft.Windows.81SDK.Store.DirectX.Msi: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1,6.3]'.
12/27/2017 12:13:16 PM - Skipping non-applicable package Microsoft.Windows.81SDK.Store.DirectX.Msi: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1,6.3]'.
12/27/2017 12:13:16 PM - Skipping non-applicable package Microsoft.Windows.81SDK.Desktop.DirectX.Msi: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1,6.3]'.
12/27/2017 12:13:16 PM - Skipping non-applicable package Microsoft.Windows.81SDK.Desktop.DirectX.Msi: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1,6.3]'.
12/27/2017 12:13:16 PM - Skipping non-applicable package Microsoft.Net.4.7.FullRedist: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1.1,10.0.14393]'.
12/27/2017 12:13:16 PM - Skipping non-applicable package Microsoft.Net.4.7.1.FullRedist: The current OS Version '10.0.16299.0' is not in the supported version range '[6.1.1,10.0.15063]'.
12/27/2017 12:13:16 PM - Skipping non-applicable package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu: The current OS Version '10.0.16299.0' is not in the supported version range '(,6.2)'.
12/27/2017 12:13:39 PM - pkgCatalogPath is 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\SVN0AG3P.C3F\catalog.json'.
12/27/2017 12:13:42 PM - vsPkg.Version is '1.5.17334.7'.  extension.Header.Version is '1.5.17334.7'
12/27/2017 12:13:43 PM - Unable to find component in product catalog with this ID: Component.WindowsTemplateStudio2017.ProRelease.60cee341-5e8e-4db5-a1c4-e3f618500d25,version=1.5.17334.7
12/27/2017 12:13:43 PM - Install Error : System.InvalidOperationException: A value for 'Component' needs to be specified in the catalog.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion, Boolean downgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

## System

* **VS Version:** VS 2017 Enterprise 15.5.2
* **WTS Wizard Version:**
* **WTS Template Version:** Attempted to update from v 1.5.17334.7 to version 1.6.17355.2
* **Windows Build:** 16299

**Comment by LanceMcCarthy** [comment]
Apparently, this is related to #1532
