### ISSUE TITLE
New project from wizard v2.1.18124.1 omits several folders/items from project.

### ISSUE THREAD

**Issue by drchilds** [Microsoft/WindowsTemplateStudio#2261]
###  Repro steps

Create a new project using the WTS wizard, I selected:

- Nav Pane
- Prism
- Blank Page, Settings, Data Grid, Chart
- Analytics, Settings Storage, Background Task, Toast, Azure Notifications, First Run and What's new

### Expected Behavior

All required files should be included in the project and the project should build.

### Actual Behavior

Project does not build, and several project folders and files must be manually included in the project, including BackgroundTasks, several Helpers, Services, ViewModels, and Views.

## System

* **VS Version:**

15.7.1

* **WTS Wizard Version:**

v2.1.18124.1

* **WTS Template Version:**

v2.1.18124.1

* **Windows Build:**

17134.48

**Comment by sibille** [comment]
@drchilds Thanks for reporting, I'll have a look at it. 
Were the files created in the correct location and just not added to the project file?

**Comment by mrlacey** [comment]
For additional information, I've also seen this a couple of times in the past but only from a WIP dev branch and with no consistent repo. If I recall, a post action failing (without good reason) was the cause of this for me.
At the least, we should be able to detect and report this happening to get some extra telem.

**Comment by drchilds** [comment]
@sibille Correct. The files were in their expected locations, but were not included in the project itself. I'm able to reliably repro this consistently with the version specified.

**Comment by drchilds** [comment]
I didn't notice anything out of the ordinary, but I'll double check when I get a chance.

**Comment by crutkas** [comment]
@sibille would logs maybe catch something?

**Comment by sibille** [comment]
yes, there should be something in the logs. 
@drchilds I could not reproduce this locally, but I had a look in the code and I think the error is related to a change we did in the latest release to support multiproject templates. This change affected the way the projectfile is determined and what I think is happening to you is that the code that adds generated file to your project is not able to find the project file. Could you share a copy of the project to see why this is happening? 
Also if you could share a copy of your log file (you can find this on C:\ProgramData\WindowsTemplateStudio\Logs) that would be great to track down this bug.

Thanks for your help!!

**Comment by harvinders** [comment]
I have also seen this consistently, the windows version is 16299 with visual studio 15.7.1.

**Comment by sibille** [comment]
@harvinders and @drchilds, could you share a project with this error and/or log files to do further investigation. I need some more info to track this down.

**Comment by harvinders** [comment]
@sibille 

### I am not sure if for the following log I had 16299 SDK installed
I think I had got a fresh PC with 15.7.1 installed with universal windows workload (which by default installs 17134 SDK only, even when the OS version is 16299)
```
>>>>>>>>>>>>>> Log started 2018-05-11 23:11:38.844
>>>>>>>>>>>>>> Assembly File Version: 2.1.18124.1
[2018-05-11 23:11:38.926]	harvinders	11980(1)		Information	Configuration file loaded: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\astdpczl.vih\WindowsTemplateStudio.config.json
[2018-05-11 23:12:09.149]	harvinders	11980(1)		Information	Creating Windows Template Studio project...
[2018-05-11 23:12:09.172]	harvinders	11980(1)		Information	Generating the template Default to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.185]	harvinders	11980(1)		Error	Unable add project items. Ensure you have the required SDK.
[2018-05-11 23:12:11.238]	harvinders	11980(1)		Information	Generating the template MVVMBasic.Project to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.323]	harvinders	11980(1)		Information	Generating the template MVVMBasic.Project.SplitView to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.402]	harvinders	11980(1)		Information	Generating the template Blank to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.484]	harvinders	11980(1)		Information	Generating the template MVVMBasic.Page.AddViewModel to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.535]	harvinders	11980(1)		Information	Generating the template MVVMBasic.Project.SplitView.AddNavigationViewItem to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.579]	harvinders	11980(1)		Information	Generating the template Page.AddPageStyle to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.632]	harvinders	11980(1)		Information	Generating the template Page.EnsureMergedDictionaries to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.673]	harvinders	11980(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.710]	harvinders	11980(1)		Information	Generating the template Tabbed to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.809]	harvinders	11980(1)		Information	Generating the template MVVMBasic.Page.AddViewModel to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.864]	harvinders	11980(1)		Information	Generating the template MVVMBasic.Project.SplitView.AddNavigationViewItem to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.906]	harvinders	11980(1)		Information	Generating the template Page.AddPageStyle to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.958]	harvinders	11980(1)		Information	Generating the template Page.EnsureMergedDictionaries to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:11.998]	harvinders	11980(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:12.043]	harvinders	11980(1)		Information	Generating the template Settings Storage to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:12.964]	harvinders	11980(1)		Information	Generating the template Settings to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:13.111]	harvinders	11980(1)		Information	Generating the template MVVMBasic.Page.AddViewModel to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:13.179]	harvinders	11980(1)		Information	Generating the template MVVMBasic.Project.SplitView.Page.Settings to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:13.251]	harvinders	11980(1)		Information	Generating the template Page.AddPageStyle to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:13.302]	harvinders	11980(1)		Information	Generating the template Page.EnsureMergedDictionaries to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:13.335]	harvinders	11980(1)		Information	Generating the template Page.Settings.AddInitialization_Blank_SplitView to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:13.383]	harvinders	11980(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Projects\lucius\JVS-1\tests\TestApp.
[2018-05-11 23:12:13.531]	harvinders	11980(1)		Error	Unable add project items. Ensure you have the required SDK.
[2018-05-11 23:12:13.554]	harvinders	11980(1)		Information	Generation finished
[2018-05-11 23:12:13.858]	harvinders	11980(1)		Error	There was an error restoring the packages. Ex: System.ArgumentException: Package 'Microsoft.NETCore.Platforms' to be uninstalled could not be found in project 'TestApp'
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewUninstallPackageAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<UninstallPackageAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageUninstaller.<>c__DisplayClass8_0.<<UninstallPackage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageUninstaller.UninstallPackage(Project project, String packageId, Boolean removeDependencies)
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.RestorePackages()
```
### For following log (for a simple code behind project) I have both the SDKs (16299 and 17134) installed
```
>>>>>>>>>>>>>> Log started 2018-05-22 21:27:00.670
>>>>>>>>>>>>>> Assembly File Version: 2.1.18124.1
[2018-05-22 21:27:00.912]	harvinders	15716(1)		Information	Configuration file loaded: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\ASTDPCZL.VIH\WindowsTemplateStudio.config.json
[2018-05-22 21:27:18.073]	harvinders	15716(1)		Information	Creating Windows Template Studio project...
[2018-05-22 21:27:18.094]	harvinders	15716(1)		Information	Generating the template Default to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:29.921]	harvinders	15716(1)		Information	Generating the template CodeBehind.Project to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:29.996]	harvinders	15716(1)		Information	Generating the template CodeBehind.Project.SplitView to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.070]	harvinders	15716(1)		Information	Generating the template Blank to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.145]	harvinders	15716(1)		Information	Generating the template CodeBehind.Page.AddINotifyPropertyChanged to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.189]	harvinders	15716(1)		Information	Generating the template CodeBehind.Project.SplitView.AddNavigationViewItem to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.235]	harvinders	15716(1)		Information	Generating the template Page.AddPageStyle to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.297]	harvinders	15716(1)		Information	Generating the template Page.EnsureMergedDictionaries to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.335]	harvinders	15716(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.382]	harvinders	15716(1)		Information	Generating the template Blank to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.448]	harvinders	15716(1)		Information	Generating the template CodeBehind.Page.AddINotifyPropertyChanged to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.489]	harvinders	15716(1)		Information	Generating the template CodeBehind.Project.SplitView.AddNavigationViewItem to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.532]	harvinders	15716(1)		Information	Generating the template Page.AddPageStyle to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.596]	harvinders	15716(1)		Information	Generating the template Page.EnsureMergedDictionaries to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.637]	harvinders	15716(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:30.681]	harvinders	15716(1)		Information	Generating the template Settings Storage to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:31.865]	harvinders	15716(1)		Information	Generating the template Settings to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:32.017]	harvinders	15716(1)		Information	Generating the template CodeBehind.Page.AddINotifyPropertyChanged to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:32.054]	harvinders	15716(1)		Information	Generating the template CodeBehind.Page.Settings.AddInitialization_Blank_SplitView to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:32.107]	harvinders	15716(1)		Information	Generating the template CodeBehind.Project.SplitView.Page.Settings to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:32.161]	harvinders	15716(1)		Information	Generating the template Page.AddPageStyle to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:32.215]	harvinders	15716(1)		Information	Generating the template Page.EnsureMergedDictionaries to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:32.257]	harvinders	15716(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Users\harvinders\source\repos\App1\App1.
[2018-05-22 21:27:43.743]	harvinders	15716(1)		Information	Generation finished
[2018-05-22 21:27:54.868]	harvinders	15716(1)		Error	There was an error restoring the packages. Ex: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source http://localnugetserver/nuget/feed. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'tenuget'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServerWarningLogHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.StsAuthenticationHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSourceAuthenticationHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.TimeoutUtility.<StartWithTimeout>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Protocol.HttpRetryHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetThrottledResponse>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ODataServiceDocumentUtils.<CreateODataServiceDocumentResourceV2>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at ODataServiceDocumentUtils.<CreateODataServiceDocumentResourceV2>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ODataServiceDocumentResourceV2Provider.<TryCreate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.MetadataResourceV2FeedProvider.<TryCreate>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<GetSourceRepository>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.RunJTFWithCorrectContext(Project project, Func`1 asyncTask)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.RestorePackages()

```
and I get the compilation error 
```
1>C:\Users\harvinders\source\repos\App1\App1\App1.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'
1>CSC : error CS2001: Source file 'C:\Users\harvinders\source\repos\App1\App1\obj\x86\Debug\App.g.i.cs' could not be found.

```
### Also, I did a MVVM project today, it compiles properly without issues.

**Comment by sibille** [comment]
Thank @harvinders !!

So the addition of project items seems to be related to installed SDKs. I'll set up a test machine to verify and solve this issue. 
The compilation error is related to the restore exception. There should be a nuget package Microsoft.NETCore.UniversalWindowsPlatform (version 6.0.8) in your project, if it got deleted and you re-add it, your project should compile

**Comment by drchilds** [comment]
Strange... I upgraded Visual Studio to 15.7.2 last night, and tried to reproduce this issue this morning. I apologize for the delay, but it looks like @harvinders, has some good repro data. 
This time, WTS seemed to update its templates, but it still had the same version numbers on the wizard. Project generation seemed to take longer, but all the files appear to be included in the project now, and it does build. Also I should note that I do have 15.8.0 Preview 1.1 installed as well.

Here is my log if it's still useful:




```
>>>>>>>>>>>>>> Log started 2018-05-22 09:14:46.630
>>>>>>>>>>>>>> Assembly File Version: 2.1.18124.1
[2018-05-22 09:14:46.703]	Dave	19676(1)		Information	Configuration file loaded: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\EXTENSIONS\ASTDPCZL.VIH\WindowsTemplateStudio.config.json
[2018-05-22 09:15:17.712]	Dave	19676(1)		Warning	The folder C:\ProgramData\WindowsTemplateStudio\Templates\Pro\2.1.18124.1_tmp can't be rename. Error: Cannot create a file when that file already exists.

===================== Exception Info =====================
System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Microsoft.Templates.Core.Fs.SafeRenameDirectory(String dir, String dirNewName, Boolean warnOnFailure)
----------------------------------------------------------
[2018-05-22 09:16:17.876]	Dave	19676(1)		Information	Creating Windows Template Studio project...
[2018-05-22 09:16:17.904]	Dave	19676(1)		Information	Generating the template Default to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:29.511]	Dave	19676(1)		Information	Generating the template Prism.Project.Blank.AddNavigation to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:29.558]	Dave	19676(1)		Information	Generating the template Prism.Project.SplitView to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:29.626]	Dave	19676(1)		Information	Generating the template Blank to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:29.706]	Dave	19676(1)		Information	Generating the template Prism.Page.AddViewModel to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:29.772]	Dave	19676(1)		Information	Generating the template Prism.Project.SplitView.AddNavigationViewItem to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:29.817]	Dave	19676(1)		Information	Generating the template Page.AddPageStyle to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:29.874]	Dave	19676(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:29.933]	Dave	19676(1)		Information	Generating the template Sample Data to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:30.024]	Dave	19676(1)		Information	Generating the template Telerik Data Grid to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:31.390]	Dave	19676(1)		Information	Generating the template Prism.Page.AddViewModel to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:31.462]	Dave	19676(1)		Information	Generating the template Prism.Project.SplitView.AddNavigationViewItem to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:31.512]	Dave	19676(1)		Information	Generating the template Page.AddPageStyle to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:31.569]	Dave	19676(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:31.630]	Dave	19676(1)		Information	Generating the template Chart to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:32.844]	Dave	19676(1)		Information	Generating the template Prism.Page.AddViewModel to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:32.920]	Dave	19676(1)		Information	Generating the template Prism.Project.SplitView.AddNavigationViewItem to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:32.971]	Dave	19676(1)		Information	Generating the template Page.AddPageStyle to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:33.033]	Dave	19676(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:33.095]	Dave	19676(1)		Information	Generating the template Tabbed to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:33.200]	Dave	19676(1)		Information	Generating the template Prism.Page.AddViewModel to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:33.288]	Dave	19676(1)		Information	Generating the template Prism.Project.SplitView.AddNavigationViewItem to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:33.344]	Dave	19676(1)		Information	Generating the template Page.AddPageStyle to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:33.406]	Dave	19676(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:33.466]	Dave	19676(1)		Information	Generating the template Settings Storage to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:34.584]	Dave	19676(1)		Information	Generating the template Settings to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:34.718]	Dave	19676(1)		Information	Generating the template Prism.Page.AddViewModel to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:34.785]	Dave	19676(1)		Information	Generating the template Prism.Project.SplitView.Page.Settings to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:34.842]	Dave	19676(1)		Information	Generating the template Page.AddPageStyle to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:34.906]	Dave	19676(1)		Information	Generating the template Project.SplitView.AddNavigationPaneRessources to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:34.960]	Dave	19676(1)		Information	Generating the template VS App Center Analytics to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:36.044]	Dave	19676(1)		Information	Generating the template Background Task to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:36.166]	Dave	19676(1)		Information	Generating the template Toast Notifications to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:37.241]	Dave	19676(1)		Information	Generating the template Azure Notifications to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:38.373]	Dave	19676(1)		Information	Generating the template Dev Center Notifications to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:39.961]	Dave	19676(1)		Information	Generating the template Live Tile to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:41.513]	Dave	19676(1)		Information	Generating the template First Run Prompt to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:43.177]	Dave	19676(1)		Information	Generating the template What's New Prompt to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:16:44.754]	Dave	19676(1)		Information	Generating the template Feedback Hub Link to C:\Users\Dave\source\repos\App3\App3.
[2018-05-22 09:17:25.384]	Dave	19676(1)		Information	Generat
```ion finished

**Comment by sibille** [comment]
@drchilds, glad that works now. There was no update to the templates or wizard since 2.1.18124.1 so WTS should not need to update the templates after VS Update, I'll open a separate issue to investigate why this is happening.

**Comment by sibille** [comment]
I could not reproduce this, but was reviewing the code on how items are added. We're currently using the DTE, but can also use the VSSolution service. I'll change this, and create a new dev-nightly build.

**Comment by sibille** [comment]
@drchilds and @harvinders, this should be fixed in the dev-nightly build, you can install it following this [instructions](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md).

**Comment by harvinders** [comment]
I have a solution with around 50 projects and I am using VS 2017 15.7.2 with both 16299 and 17134 SDK installed. Today I saw another issue, wherein adding a new WTS project was exhibiting the same issue mentioned in this ticket.

I have just installed the nightly WTS and tried again and I can confirm nightly solves the problem. Then I uninstalled the nightly and with the stable release, I am able to reproduce the problem.

**Comment by sibille** [comment]
thanks @harvinders! Version 2.2 will be released in aprox 2 weeks
