### ISSUE TITLE
UWP Unit Tests are not discoverable using MVVM Light

### ISSUE THREAD

**Issue by pwang347** [Microsoft/WindowsTemplateStudio#2277]
### Repro steps

1. Create a new Windows Template Studio (Universal Windows) project that uses the MVVM Light framework (e.g. Blank, with all default options otherwise)
2. Create a new Unit Test App (Universal Windows) project and add a reference to the previously created project
3. Run the provided placeholder test suite (ie. Test > Run > All Tests)

### Expected Behavior

The placeholder test suite is discovered and run.

### Actual Behavior

Error output:
```
[5/21/2018 10:32:34 PM Informational] ------ Discover test started ------
[5/21/2018 10:33:03 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
[5/21/2018 10:33:03 PM Informational] ========== Discover test finished: 0 found (0:00:28.8141373) ==========
[5/21/2018 10:33:03 PM Informational] ------ Run test started ------
[5/21/2018 10:33:08 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[5/21/2018 10:33:08 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[5/21/2018 10:33:08 PM Informational] ========== Run test finished: 0 run (0:00:05.0143519) ==========

```

## System

* **VS Version:** 15.7.1
* **WTS Wizard Version:** 2.1.18124.1
* **WTS Template Version:** 2.1.18124.1
* **Windows Build:** 16299

### Additional Note
Following the discussion at https://github.com/Windows-XAML/Template10/issues/464, adding the `[Bindable]` attribute to the ViewModelLocator class fixed the above issue for me.

**Comment by mrlacey** [comment]
Verifying which frameworks this effects as I suspect it's more than just MVVM Light.

**Comment by mrlacey** [comment]
Impacted scenarios:
- MVVM Light (C# & VB)
- Caliburn.Micro
- Prism

No impact if using Code-Behind or MVVMBasic

**Comment by mrlacey** [comment]
@pwang347 Thanks for reporting this issue. It will be addressed in the next nightly build.

**Comment by mrlacey** [comment]
Verified in 
Templates version: 0.18.18143.2
Wizard version: 0.18.18143.1
