### ISSUE TITLE
App crash on Prism Framework

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2279]
### Repro steps
 - Create a new app with the following configuration
   -  Project type: Blank
   -  Framework: Prism
   -  Pages: Only one page ImageGallery as main page.
   -  Features: SampleData & SettingStorage added as dependencies of ImageGallery page.

 - Launch the app in Debug Mode
 - Navigate to an image detail.
 - Go back to the images list.
 - Close the app (X button).

You can also checkout this bug on this Bug-Repro application [PrismBugImageGallery.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2025483/PrismBugImageGallery.zip)

### Expected Behavior

The App is closed and the debugging proccess stops.

### Actual Behavior

The App throws an exception.

**Exception Message**
"Session state service failed"

**Source**
Prism.Windows

**Exception StackTrace**
at Prism.Windows.AppModel.SessionStateService.<SaveAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Prism.Windows.PrismApplication.<OnSuspending>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

**InnerException Message**
"Unspecified error: GetNavigationState doesn't support serialization of a parameter type which was passed to Frame.Navigate."

**InnerException StackTrace**
at Windows.UI.Xaml.Controls.Frame.GetNavigationState()
at Prism.Windows.Navigation.FrameFacadeAdapter.GetNavigationState()
at Prism.Windows.AppModel.SessionStateService.<SaveAsync>d__5.MoveNext()

## System

* **VS Version: 15.7.1**
* **WTS Wizard Version: 2.1.18124.1**
* **WTS Template Version: 2.1.18124.1**
* **Windows Build: 1803 - 17134.48**

**Comment by crutkas** [comment]
Is this a production issue

**Comment by sibille** [comment]
yes
