### ISSUE TITLE
Object Instance not set

### ISSUE THREAD

**Issue by IsaacMorris1980** [Microsoft/WindowsTemplateStudio#2298]
I am on Windows Beta( will be filling out bug with them as well and also one with Visual Studios) Build 17672, When i try to create a UWP  app using the template studios i get the error object instance not set to object.

I think this is Visual Studios Bug but just creating bug in case it is template studio issue.

The following error displays in VS 2017 15.7.1 console:

========= Exception Tracked [2018-05-22 19:52:03.204] ==========
[19:52:03.216 - Information]::Configuration file loaded: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\ASTDPCZL.VIH\WindowsTemplateStudio.config.json
Additional Message: Critical error initializating GenContext.
System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at Microsoft.VisualStudio.Setup.Configuration.ISetupConfiguration.GetInstanceForCurrentProcess()
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.GetVsVersionAndInstance()
   at Microsoft.Templates.Core.Gen.GenContext.Bootstrap(TemplatesSource source, GenShell shell, Version wizardVersion, String language)
   at Microsoft.Templates.UI.VisualStudio.SolutionWizard.Initialize(String language)
   at Microsoft.Templates.UI.VisualStudio.SolutionWizardCS..ctor()

Visual Studios Version: 15.7.1

Windows 10 Build:  17672

UWP Template Studio Version:  2.1.18124.1
Steps to Reproduce:
VS = Visual Studios
1.  Install Windows Insider build 17672
2.  Install VS 2017 15.7.1
3.  Install UWP Template Stuid 2.1.18124.1
4.  Open VS2017
5. Click File
6. Click New Project
7. Select Template Studio
8.  Select ok or next
9.  Error occurs in console nothing displays on screen

Expected Behavior:
Template Studio wizard to display allowing for project creation

Actual Behavior:
Error displays in console wizard does not display however seeing the message i am not surprised that wizard does not display

**Comment by crutkas** [comment]
Do you have sdk 17672 installed?

**Comment by IsaacMorris1980** [comment]
It installed with my build will recheck

**Comment by IsaacMorris1980** [comment]
Closing ticket issue was a ccleaner and ccenhancer cleanup issue, re-installed  VS 2017 and did not re-run ccleaner, issue is resolved
