### ISSUE TITLE
Dev-nightly: Error in master detail Page when navigating second time to the page

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2738]
1. Create an app with ProjectType SplitView and framework Mvvmlight
2. Add a MasterDetail page

3. Start the app
4. Navigate to the MasterDetail page
5. Go to another page

6. Go to the MasterDetail page again:

-> Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Toolkit.Uwp.UI.Controls.MasterDetailsView.SetBackButtonVisibility(Nullable`1 previousState)
   at Microsoft.Toolkit.Uwp.UI.Controls.MasterDetailsView.UpdateViewState()
   at Microsoft.Toolkit.Uwp.UI.Controls.MasterDetailsView.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at Windows.UI.Xaml.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Microsoft

Repro app:  [MVVMLightMasterDetailRepro.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2553966/MVVMLightMasterDetailRepro.zip)

**Comment by skendrot** [comment]
Is there a custom style for the MasterDetailsView?

**Comment by skendrot** [comment]
Found the issue one [line 317](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI.Controls/MasterDetailsView/MasterDetailsView.cs#L317)

A quick work-around for WTS is to not set the selected item by removing this line:
```
Selected = SampleItems.First();
```

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.19.18316.1
Wizard version: 0.19.18316.1
