### ISSUE TITLE
project generation error at localization file.

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#2909]
## For Bugs:

**Error details**

System.Exception: Error executing 'Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction'. Related template: wts.Feat.SettingsStorage. ---> System.IO.FileNotFoundException: There is no merge target for file 'C:\Users\touse\source\Workspaces\365 JMS\GI_Chat\GI Chat 365\GI_Chat_365\Strings\en-us\Resources_postaction.resw'. Related Template: 'wts.Feat.SettingsStorage'.
   at Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction.HandleFileNotFound(String originalFilePath, String suffix)
   at Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction.ExecuteInternal()
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   at Microsoft.Templates.Core.Gen.GenController.ExecutePostActions(GenInfo genInfo, TemplateCreationResult generationResult)
   at Microsoft.Templates.Core.Gen.GenController.<GenerateItemsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.Core.Gen.NewProjectGenController.<UnsafeGenerateProjectAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.Services.GenerationService.<GenerateProjectAsync>d__5.MoveNext()

### Repro steps

Created a new project with wts Selected blank project type, mvvm-basic, just 1 page ( Master-Detail ) and selected deep linking and multiple-views in features, and then pressed create.

### Expected Behavior

the project should generate completely without any problem.

## System

* **VS Version:** VS 2017 15.9.6
* **WTS Wizard Version:** 3.0.19031.2
* **WTS Template Version:** 3.0.19031.2
* **Windows Build:** 1809

**Comment by crutkas** [comment]
Thanks for reporting this.  We have a fix for this (was reported in #2892) and should be pushing out a hotfix shortly.
