### ISSUE TITLE
Access to the path x is denied

### ISSUE THREAD

**Issue by HADDADENICAR** [microsoft/WindowsTemplateStudio#3178]
I want to extend my existing ***aspNetBoilerplate*** app with *windows-template-studio*, when i add my template project i get this error :

Error executing 'Microsoft.Templates.Core.PostActions.Catalog.SortNamespaces.SortUsingsPostAction'. Related template: None.
------------------------------------------------------------------------

    System.UnauthorizedAccessException: Access to the path 'F:\tfs\Guichet\V3.1\src\Guichet.Application\GuichetAppServiceBase.cs' is denied.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
       at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
       at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
       at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents, Encoding encoding)
       at Microsoft.Templates.Core.PostActions.Catalog.SortNamespaces.SortNamespacesPostAction.ExecuteInternal()
       at Microsoft.Templates.Core.PostActions.PostAction.Execute()
       --- End of inner exception stack trace ---
       at Microsoft.Templates.Core.PostActions.PostAction.Execute()
       at Microsoft.Templates.Core.Gen.GenController.ExecuteGlobalPostActions()
       at Microsoft.Templates.Core.Gen.GenController.<GenerateItemsAsync>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Templates.Core.Gen.NewProjectGenController.<UnsafeGenerateProjectAsync>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Templates.UI.Services.GenerationService.<GenerateProjectAsync>d__5.MoveNext()

I changed the control  of the specified file to FullControl but the error dosen't disappear !  
That happens just with windows Template studio,a blank uwp have no issue.
Any idea ?

**Comment by mrlacey** [comment]
Can you explain what you mean by "when i add my template project"? Add it to what?

I'm trying to understand what you're doing so we can recreate it.

Based on the error message, is it that you're using TFS and have locked access to the folder that it's trying to add the project to?
If you try creating the app in an area not restricted by any existing repository permissions does it still happen?

**Comment by HADDADENICAR** [comment]
I have an aspNetBoilerplate project ,that I want to extend it with  windows template Studio.
I can create an independant new windows template Studio project without a problem, you said it’s a TFS security problem ? I don’t know but I can add an UWP project without any issue !

Sent from Mail for Windows 10

**Comment by mrlacey** [comment]
So I can understand what's happening.

> I have an aspNetBoilerplate project ,that I want to extend it with  windows template Studio.

So that's an existing solution and you want to add a new project to it using WinTS. Is this right?

> you said it’s a TFS security problem 

No, I said that looks like a likely cause based on the information available.

As the file path in the error message starts "F:\tfs\\" I assumed that you are using TFS for version control. Are you?
I know TFS can do things to lock files and folder paths (much more than other version control systems) and I suspect that's what's happening here.
When creating a new blank UWP project the files are just created on disk.
When creating with WinTS, lots of files are copied to disk and then combined and manipulated in other ways. (That's how we can have so many different options in the wizard and not have to have multiple copies of every file for every combination of options.) I suspect that the newly created files are being locked by TFS after they are created and that is preventing the other parts of the WinTS process from manipulating them as necessary.

As a workaround. I suggest creating the project in a different location on disk and then copying into your existing solution structure.

**Comment by sibille** [comment]
@HADDADENICAR, thanks for reporting!

I'm trying to reproduce this. Is "F:\tfs\Guichet\V3.1\src\Guichet.Application\GuichetAppServiceBase.cs" part of your WTS project or part of your aspNetBoilerplate project?

**Comment by HADDADENICAR** [comment]
@sibille it's part of  my aspNetBoilerplate project

**Comment by sibille** [comment]
Thanks @HADDADENICAR, seems WTS is trying to reorder usings on files that shouldn't be touched. Could you share a schema of your project folder structure? You can replace real names with code-names, just want to understand at what level each project is created.

**Comment by HADDADENICAR** [comment]
![2019-06-10](https://user-images.githubusercontent.com/35377776/59180828-33977600-8b66-11e9-9d5d-373b684e306c.png)

does this what you mean by schema of my project folder ?
Initialy the solution dosen't have uwp , iadded it as solution to make my (master/detail)  following [this](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/XamlMasterDetail)

**Comment by sibille** [comment]
Thanks! I was refering to this but on file system, sth like this
![image](https://user-images.githubusercontent.com/24698018/59181426-a2290380-8b67-11e9-9e90-95130a257541.png)

**Comment by HADDADENICAR** [comment]
![2019-06-10 (1)](https://user-images.githubusercontent.com/35377776/59181711-52970780-8b68-11e9-87ae-2a447b91f72c.png)

**Comment by sibille** [comment]
@HADDADENICAR I was able to reproduce this and am working on a fix for this. Thanks for reporting!
X-Ref: https://github.com/microsoft/CoreTemplateStudio/issues/160

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19178.1
Wizard version: 0.20.19178.1
