### ISSUE TITLE
Can't create new files using Windows Template Studio after renaming the project

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsTemplateStudio#3811]
**Describe the bug**
After you rename a project, you can no longer create a new file using Windows Template Studio.

**To Reproduce**
1. Create a new project using Windows Template Studio
2. Rename it
3. Right click on the project, select Windows Template Studio and click on any option

**Expected behavior**
Windows Template Studio should work properly after renaming a project.

**Screenshots**

**Additional context**
```
System.Exception: Error executing 'Microsoft.Templates.Core.PostActions.Catalog.AddContextItemsToSolutionAndProjectPostAction'. Related template: None. ---> System.Exception: Error adding items to project C:\Users\jaiga\source\repos\CodeEditor\CodeEditor\FineDevelop.csproj ---> System.Runtime.InteropServices.COMException: Cannot find file "C:\Users\jaiga\source\repos\CodeEditor\CodeEditor\Views\TestPage.xaml".
   at EnvDTE.ProjectItems.AddFromFile(String FileName)
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.<>c__DisplayClass13_0.<<AddItems>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.AddItems(String projPath, IEnumerable`1 projFiles)
   --- End of inner exception stack trace ---
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.AddItems(String projPath, IEnumerable`1 projFiles)
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.AddContextItemsToSolution(ProjectInfo projectInfo)
   at Microsoft.Templates.Core.PostActions.Catalog.AddContextItemsToSolutionAndProjectPostAction.ExecuteInternal()
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   at Microsoft.Templates.Core.Gen.NewItemGenController.ExecuteSyncGenerationPostActions(TempGenerationResult result)
   at Microsoft.Templates.Core.Gen.NewItemGenController.UnsafeFinishGeneration(UserSelection userSelection)
   at Microsoft.Templates.UI.Services.GenerationService.FinishGeneration(UserSelection userSelection)
```

Applies to the following platforms:
- [x] UWP
- [ ] WPF

**System**

- **VS Version: 16.7.2** 
- **WinTS Wizard Version: 3.7.20203.3** 
- **WinTS Template Version: 3.7.20203.3** 
- **Windows Build: 19041.450**

**Comment by sibille** [comment]
I have to look deeper into this but think that we can check if the project name matches the expected directory structure and display a warning in this case so the dev can adjust to what we expect (I think if you change the folder name + project name + default namespace the addition should work fine.
In case the dev decides to proceed without changes I see two options:
 - Pre-select the option 'do not merge changes (generate in a temp folder)' as Matt suggested 
- Offer the possibility to try to merge changes and log failed postactions instead of throwing an exception so the dev is aware of the steps we could not execute and can do them manually

**Comment by sibille** [comment]
Sorry for the delay @Jaiganeshkumaran, looking into this for milestone 3.9

**Comment by sibille** [comment]
I had a look into this, and we can easily detect that the project name and folder structure are different from what we expect when adding new items. We should show a warning in this case as the generation might be incomplete and will fail on integration in the case you describe (rename a project after generation without renaming the folder). If you rename both the project and the folder everything should work fine again.

Regarding the question if we should pre-select the "do not merge changes" check or allow integration and alert on errors I think  pre-selecting (and disabling) the "do not merge changes" check is the better option. This leaves the generated files in a temporary folder and gives instructions on how to manually integrate them. 

Looking at the alternative (try to merge changes and alert on failures) I saw that all actions fail and the files get copied in the wrong folder (a combination of solution folder path + new project name) which seems more confusing than helpful to me.

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.20337.1
Wizard version: 0.22.20335.2
