### ISSUE TITLE
Grid page throwing TargetParameterCountException in VS designer

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#496]
TargetParameterCountException: Parameter count mismatch.  Tried both codebehind and MVVM Light.  

recipe: navpane, code behind, grid page
Nightly and pre-release throwing

**stack trace:**
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Telerik.Data.Core.BindingExpressionHelper.<>c__DisplayClass0_0.<CreateGetValueFunc>b__0(Object item)
   at Telerik.Data.Core.Fields.PropertyInfoFieldInfo.GetValue(Object item)
   at Telerik.UI.Xaml.Controls.Grid.DataGridTypedColumn.GetValueForInstance(Object instance)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.Telerik.UI.Xaml.Controls.Grid.ITable.GetCellValue(ItemInfo rowItemInfo, ItemInfo columnItemInfo)
   at Telerik.UI.Xaml.Controls.Grid.CellsController`1.GetCellDecorator(IItemInfoNode parentRow, ItemInfo columnItemInfo, Int32 rowLine, Int32 columnLine)
   at Telerik.UI.Xaml.Controls.Grid.CellsController`1.GenerateCellsForRow(IItemInfoNode rowDecorator, Int32 rowSlot)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.GenerateCellsForReadOnlyRow(Int32 rowSlot, Double largestRowElementWidth, IItemInfoNode rowDecorator)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.Telerik.UI.Xaml.Controls.Grid.ITable.GenerateCellsForRow(Int32 rowSlot, Double largestRowElementHeight, IItemInfoNode rowDecorator)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.GenerateCellsForLine(Int32 slot, Double largestLength, T lastElement)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.GenerateContainer(IList`1 itemInfos)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.MeasureForward(MeasureContext& context)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.MeasureVertically(RadSize availableSize, Double offset, Double bufferScale)
   at Telerik.UI.Xaml.Controls.Grid.NodePool`2.OnMeasure(RadSize availableSize, Double offset, Int32 frozenElementsCount, Double verticalBufferScale)
   at Telerik.UI.Xaml.Controls.Grid.Model.GridModel.MeasureCells(RadSize newAvailableSize)
   at Telerik.UI.Xaml.Controls.Grid.RadDataGrid.OnCellsPanelMeasure(RadSize newAvailableSize)
   at Telerik.UI.Xaml.Controls.Grid.Primitives.DataGridCellsPanel.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
   at Telerik.UI.Xaml.Controls.Grid.Primitives.DataGridRootPanel.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Telerik.UI.Xaml.Controls.RadControl.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.UIElement.UpdateLayout()
   at Microsoft.VisualStudio.DesignTools.UwpDesigner.Views.UwpImageHost.WindowsXamlSceneWrapper.UpdateLayout()
   at Microsoft.VisualStudio.DesignTools.UwpDesigner.Views.UwpImageHost.set_RootInstance(Object value)

**Comment by mvegaca** [comment]
This Issue was already created on Telerik UWP Controls GitHub.

[TargetParameterCountException when binding ItemsSource with x:Bind expression
](https://github.com/telerik/UI-For-UWP/issues/84)

I've check that this Issue being fixed using Binding instead of x:Bind but all templates are implementing x:Bind in all different frameworks.

**Comment by mvegaca** [comment]
Telerik team will apply a fix for this issue in the next few days in order to prevent the designer from crushing when x:Bind is used.

**Comment by crutkas** [comment]
We'll change from x:bind to binding as a quick work around now.  comment the template why this is like it is.  Keep this bug open and wait for the update to Telerik to change.

https://github.com/telerik/UI-For-UWP/issues/84

**Comment by crutkas** [comment]
Looks like Telerik have a fix for this.  asking for ETA for new nuget update from them

**Comment by crutkas** [comment]
they said next few days

**Comment by ralarcon** [comment]
Well, once available, we'll rollback the workaround.

**Comment by crutkas** [comment]
new nuget is out that should contain this fix.  https://www.nuget.org/packages/Telerik.UI.for.UniversalWindowsPlatform
