### ISSUE TITLE
Locally built VSIX not offline enabled?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#512]
![image](https://user-images.githubusercontent.com/1462282/27541598-5cdb7274-5a39-11e7-8a0c-78bfc9f69d9b.png)
I built a local version, offline, shouldn't I have gotten everything?

**Comment by ralarcon** [comment]
Yes, it should be all loaded... Does this happened the very first time you run the local vsix?

I pretty sure what you are experiencing... Let me try to explain:

To allow to deliver the templates content within the vsix (to avoid to be connected on the fisrt run) we have added a Templates.mstx package within the VSIX Content folder. During the release generation process (server builds) that Templates.mstx is being replaced with the most current and aligned version of the templates. 

The templates.mstx in the source code of vsix package is from a certain version and it is not refreshed every time you locally build. And what you are experiencing is that the content is not aligned with the changes we have in the wizard.

We can think in a way to generate a local VSIX version which ensures the content is aligned with the VSIX, but this only should happen the very first time you run the VSIX (as it is detected that there is no content available and the content is extracted from the delivered Templates.mstx package).

This should be fixed in the issue276-rightclick branch.

**Comment by crutkas** [comment]
happens all the time.  here is the error log.  On running now, i see this

[12:42:35.453 - Verbose]::Current content expiration: 5/15/2017 7:20:57 PM
[12:42:35.485 - Error]::Microsoft.Templates.Core.RepositorySynchronizationException: Error syncing templates. Status: 'Adquiring' ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Templates'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Microsoft.Templates.Core.Locations.Fs.CopyRecursive(String sourceDir, String targetDir)
   at Microsoft.Templates.Core.Locations.LocalTemplatesSource.Copy(String sourceFolder, String targetFolder)
   at Microsoft.Templates.Core.Locations.LocalTemplatesSource.AcquireMstx()
   at Microsoft.Templates.Core.Locations.TemplatesSource.Acquire(String targetFolder)
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.AdquireContent()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.AdquireContent()
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.<AdquireContentAsync>b__24_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.<AdquireContentAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.<CheckExpirationAdquisitionAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.<Do>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.Core.TemplatesRepository.<SynchronizeAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.UI.ViewModels.MainViewModel.<InitializeAsync>d__77.MoveNext()
========== Tracked Exception [20170628 12:42:35.500] ==========
Microsoft.Templates.Core.RepositorySynchronizationException: Error syncing templates. Status: 'Adquiring' ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Templates'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Microsoft.Templates.Core.Locations.Fs.CopyRecursive(String sourceDir, String targetDir)
   at Microsoft.Templates.Core.Locations.LocalTemplatesSource.Copy(String sourceFolder, String targetFolder)
   at Microsoft.Templates.Core.Locations.LocalTemplatesSource.AcquireMstx()
   at Microsoft.Templates.Core.Locations.TemplatesSource.Acquire(String targetFolder)
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.AdquireContent()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.AdquireContent()
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.<AdquireContentAsync>b__24_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.<AdquireContentAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.<CheckExpirationAdquisitionAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.Core.Locations.TemplatesSynchronization.<Do>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.Core.TemplatesRepository.<SynchronizeAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Templates.UI.ViewModels.MainViewModel.<InitializeAsync>d__77.MoveNext()
--------------------------------------------------------------

**Comment by mrlacey** [comment]
I think this might be down to your path setup.  (It seems odd to me this should be looking under "Program Files")

Anyway, a while back something was changed that meant it broke template paths containing spaces. I discovered this when I updated the VB branch from dev. VB templates must work with spaces (they contain a "My Project" folder) and so I had to put in a fix for this issue there. Not saying for sure this is the same thing but that's where I'd start looking further. 

My fix for this in the VB branch should be submitted to dev without templates later this week if you can hold on until then.

**Comment by ralarcon** [comment]
I'll have a closer look on this today

**Comment by mrlacey** [comment]
is this still an issue?

**Comment by ralarcon** [comment]
Last refactors for LocalTemplatesSource  Verifed and didn't able to repro. So closing.
