### ISSUE TITLE
Getting project creation failed

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#609]
![image](https://user-images.githubusercontent.com/1462282/27874242-b4785034-6163-11e7-8d66-1977de78b1a0.png)

Ran the wizard once to see the nightly and started seeing this after I cancelled out.

```
>>>>>>>>>>>>>> Log started 20170705 08:42:58.943
>>>>>>>>>>>>>> Assembly File Version: 0.14.17180.65001
[20170705 08:42:59.027]	crutkas	356864(1)		Information	Configuration file loaded: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\21VJ3PXX.MKO\WindowsTemplateStudio.config.json
[20170705 08:43:00.054]	crutkas	356864(1)		Verbose	Current content expiration: 6/29/2017 3:47:58 PM
[20170705 08:43:01.038]	crutkas	356864(12)		Verbose	Templates content downloaded to C:\Users\crutkas\AppData\Local\Temp\cp04drmm.cfu\Templates.mstx from https://wtsrepository.blob.core.windows.net/dev/Latest/Templates.mstx.
[20170705 08:43:01.068]	crutkas	356864(12)		Verbose	Package certificate OID.0.9.2342.19200300.100.1.1=10018646, CN=Microsoft Windows App Studio, OU=Microsoft Windows App Studio
[20170705 08:43:02.826]	crutkas	356864(12)		Verbose	Templates content extracted to C:\Users\crutkas\AppData\Local\Temp\d4n4cwup.wlm.
[20170705 08:47:01.041]	crutkas	356864(1)		Verbose	Current content expiration: 7/5/2017 10:43:03 AM

>>>>>>>>>>>>>> Log started 20170705 08:51:17.280
>>>>>>>>>>>>>> Assembly File Version: 0.14.17186.65008
[20170705 08:51:17.321]	crutkas	350816(1)		Information	Configuration file loaded: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\P22WACVZ.F2A\WindowsTemplateStudio.config.json
[20170705 08:51:17.605]	crutkas	350816(1)		Verbose	Next automatic content verification at 7/5/2017 10:43:03 AM
[20170705 08:51:17.677]	crutkas	350816(1)		Verbose	Next automatic content verification at 7/5/2017 10:43:03 AM

>>>>>>>>>>>>>> Log started 20170705 09:25:38.523
>>>>>>>>>>>>>> Assembly File Version: 0.14.17186.65008
[20170705 09:25:38.567]	crutkas	357736(1)		Information	Configuration file loaded: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\P22WACVZ.F2A\WindowsTemplateStudio.config.json
[20170705 09:25:38.811]	crutkas	357736(1)		Verbose	Next automatic content verification at 7/5/2017 10:43:03 AM
[20170705 09:25:38.880]	crutkas	357736(1)		Verbose	Next automatic content verification at 7/5/2017 10:43:03 AM
[20170705 09:25:44.259]	crutkas	357736(1)		Verbose	Next automatic content verification at 7/5/2017 10:43:03 AM
[20170705 09:25:44.276]	crutkas	357736(1)		Verbose	Next automatic content verification at 7/5/2017 10:43:03 AM
[20170705 09:26:07.125]	crutkas	357736(10)		Verbose	Templates content downloaded to C:\Users\crutkas\AppData\Local\Temp\335x4d5w.agm\Templates.mstx from https://wtsrepository.blob.core.windows.net/dev/Latest/Templates.mstx.
[20170705 09:26:07.160]	crutkas	357736(10)		Verbose	Package certificate OID.0.9.2342.19200300.100.1.1=10018646, CN=Microsoft Windows App Studio, OU=Microsoft Windows App Studio
[20170705 09:26:08.724]	crutkas	357736(10)		Verbose	Templates content extracted to C:\Users\crutkas\AppData\Local\Temp\sinflcqq.kwx.
[20170705 09:26:08.874]	crutkas	357736(10)		Warning	The folder C:\Users\crutkas\AppData\Local\Temp\sinflcqq.kwx can't be delete. Error: The directory is not empty.

===================== Exception Info =====================
System.IO.IOException: The directory is not empty.

   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Microsoft.Templates.Core.Fs.SafeDeleteDirectory(String dir)
----------------------------------------------------------
[20170705 09:28:23.299]	crutkas	357736(1)		Verbose	Next automatic content verification at 7/5/2017 10:43:03 AM
[20170705 09:28:23.329]	crutkas	357736(1)		Verbose	Next automatic content verification at 7/5/2017 10:43:03 AM
```
`

**Comment by crutkas** [comment]
I can't seem to reproduce the error however

**Comment by ralarcon** [comment]
Let me know if its reproduces again... looks to be related to #614 and #625... but being the nightly build the chances to colison are reduced... anyway now the process is avoiding to have "multiple verifications concurrently" so it should not fail regardin the "directory not empty" which would be the root cause.

**Comment by crutkas** [comment]
haven't seen this happen again.
