### ISSUE TITLE
Local crash on right click add in emulator

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#648]
On either "+" button i click, it crashes

public override ValidationResult Validate(string suggestedName)
        {
            var existing = Directory.EnumerateDirectories(_config)
                                            .Select(d => new DirectoryInfo(d).Name)
                                            .ToList();

System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\crutkas\AppData\Local\Temp\WTSTempGeneration'.'

System.IO.DirectoryNotFoundException occurred
  HResult=0x80070003
  Message=Could not find a part of the path 'C:\Users\crutkas\AppData\Local\Temp\WTSTempGeneration'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.Templates.Core.DirectoryExistsValidator.Validate(String suggestedName) in C:\Users\crutkas\Source\Repos\NewRepo\code\src\Core\Naming\DirectoryExistsValidator.cs:line 27
   at Microsoft.Templates.Core.Naming.<>c__DisplayClass2_0.<Infer>b__0(Validator v) in C:\Users\crutkas\Source\Repos\NewRepo\code\src\Core\Naming\Naming.cs:line 32
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Templates.Core.Naming.Infer(String suggestedName, IEnumerable`1 validators, String inferWith) in C:\Users\crutkas\Source\Repos\NewRepo\code\src\Core\Naming\Naming.cs:line 32
   at Microsoft.Templates.VsEmulator.Main.MainViewModel.GetTempGenerationPath() in C:\Users\crutkas\Source\Repos\NewRepo\code\test\VsEmulator\Main\MainViewModel.cs:line 226
   at Microsoft.Templates.VsEmulator.Main.MainViewModel.AddNewFeature() in C:\Users\crutkas\Source\Repos\NewRepo\code\test\VsEmulator\Main\MainViewModel.cs:line 198
   at Microsoft.Templates.Core.Mvvm.RelayCommand.Execute(Object parameter) in C:\Users\crutkas\Source\Repos\NewRepo\code\src\Core\Mvvm\RelayCommand.cs:line 42
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Microsoft.Templates.VsEmulator.App.Main()

**Comment by crutkas** [comment]
wrote this is in 651 but what caused this
