### ISSUE TITLE
New machine failure

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#963]
Running WTS project on new machine that has never done any file->new.  Projects folder does not exist yet.
```

System.IO.DirectoryNotFoundException occurred
  HResult=0x80070003
  Message=Could not find a part of the path 'C:\Users\crutkas\Documents\Visual Studio 2017\Projects'.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.Templates.Core.DirectoryExistsValidator.Validate(String suggestedName) in C:\Users\crutkas\source\repos\WTS\code\src\Core\Naming\DirectoryExistsValidator.cs:line 19
   at Microsoft.Templates.Core.Naming.<>c__DisplayClass2_0.<Infer>b__0(Validator v) in C:\Users\crutkas\source\repos\WTS\code\src\Core\Naming\Naming.cs:line 24
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Templates.Core.Naming.Infer(String suggestedName, IEnumerable`1 validators, String inferWith) in C:\Users\crutkas\source\repos\WTS\code\src\Core\Naming\Naming.cs:line 24
   at Microsoft.Templates.VsEmulator.NewProject.NewProjectViewModel.GetSuggestedSolution(String path) in C:\Users\crutkas\source\repos\WTS\code\test\VsEmulator\NewProject\NewProjectViewModel.cs:line 89
   at Microsoft.Templates.VsEmulator.NewProject.NewProjectViewModel.SetName() in C:\Users\crutkas\source\repos\WTS\code\test\VsEmulator\NewProject\NewProjectViewModel.cs:line 70
   at Microsoft.Templates.VsEmulator.NewProject.NewProjectViewModel.Initialize() in C:\Users\crutkas\source\repos\WTS\code\test\VsEmulator\NewProject\NewProjectViewModel.cs:line 63
   at Microsoft.Templates.VsEmulator.NewProject.NewProjectView.<.ctor>b__4_0(Object o, RoutedEventArgs e) in C:\Users\crutkas\source\repos\WTS\code\test\VsEmulator\NewProject\NewProjectView.xaml.cs:line 25
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

```

**Comment by crutkas** [comment]
have the fix, now to unit test
